### ISSUE TITLE
"beautifuly immersive worlds" – Body Copy

### ISSUE THREAD

**Issue by jordanlambrecht** [pixelbakery/pb-oct-2022#118]
Created by Jordan Lambrecht via monday.com integration. 🎉

**Comment by oliviaboldt** [comment]
We’re a collective of skilled leaders and creatives that all share the same belief: creating intentional, high-quality products that are results of purposeful visions, collaborative feedback, and not taking any shortcuts.

At PB, we operate as an adaptable extension of our client’s teams to ensure that their companies are able to rise above the visual noise, capture their audience’s attention, and continue to grow. We believe in the importance of relationships, which is why we rely on client feedback to ensure the final product will be something both sides can take pride in.

@jordanlambrecht
